### ISSUE TITLE
Love to see an example of the middleware being applied globally.

### ISSUE THREAD

**Issue by geng0610** [clerk/clerk-express-quickstart#1]
your old example had something like this.

// Extend the Express Request interface globally to include Clerk auth properties
declare global {
  namespace Express {
    interface Request extends StrictAuthProp {}
  }
}

// Apply Clerk auth middleware globally for all subsequent routes
app.use(ClerkExpressRequireAuth());

I'd love to see this with the Express app as well.

**Comment by wobsoriano** [comment]
Here you go https://clerk.com/docs/upgrade-guides/node-to-express#migrate-from-clerk-express-require-auth
